analyzers:
  ros__parameters:
    pub_rate: 1.0
    path: Diagnostics

    lidar:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Lidar
      contains: ["Lidar"]

    camera:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Camera
      contains: ["Camera"]

    imu:
      type: diagnostic_aggregator/GenericAnalyzer
      path: IMU
      contains: ["IMU"]

    gnss:
      type: diagnostic_aggregator/GenericAnalyzer
      path: GNSS
      contains: ["GNSS", "GPS"]