%YAML:1.0
board_width: 1.4        # width of board in meters
board_height: 1.0       # height of board in meters
marker_size: 0.2       # side length of aruco markers in meters
marker_ids:             # ids of marker used as a single column matrix
    rows: 4
    cols: 1
    dt: i
    data: [1, 2, 3, 4]  # marker order goes clockwise, starting from top left of board
marker_positions:       # x,y marker positions (top-left) on board relative to center, stored row-by-row in meters. x: rightwards, y: upwards
    rows: 4
    cols: 2
    dt: f
    data: [-0.65, 0.45,
           0.45, 0.45,
           0.45, -0.25,
           -0.65, -0.25]
cutouts:                # Cutouts (id + parameters) stored as a single row matrix. x: rightwards, y: upwards
    rows: 1
    cols: 16
    dt: f
    data: [1, -0.25, 0.20, 0.12,    # Circular cutout: (id: 1, parameters: {X,Y,Radius})
           1, 0.25, -0.20, 0.12,    
           1, -0.25, -0.20, 0.12,
           1, 0.25, 0.20, 0.12]   
min_marker_detection: 2 # minimum number of markers that need to be detected in the camera image
cad_model_mesh: "calibration_target_3holes_cad_mesh.ply" # relative file path to CAD model of the calibration target as mesh
cad_model_cloud: "calibration_target_3holes_cad_cloud.ply" # relative file path to CAD model of the calibration target as cloud