services:
  ptp-grandmaster:
    build:
      context: ./ptp
    container_name: ptp_grandmaster
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_TIME
    devices:
      - /dev/ptp2:/dev/ptp1
      - /dev/ptp2:/dev/ptp2
      - /dev/ptp2:/dev/ptp3
    environment:
      PTP_INTERFACE: "${PTP_INTERFACE:?PTP_INTERFACE is missing from .env}"
    volumes:
      - ./ptp/ptp4l.conf.template:/etc/linuxptp/ptp4l.conf.template:ro
    command:
      - /bin/sh
      - -ec
      - |
          echo "PTP_INTERFACE=$${PTP_INTERFACE}"
          test -n "$${PTP_INTERFACE}"

          envsubst '$${PTP_INTERFACE}' \
            < /etc/linuxptp/ptp4l.conf.template \
            > /etc/linuxptp/ptp4l.conf

          echo "Generated configuration:"
          cat /etc/linuxptp/ptp4l.conf
          echo

          grep -F "[$${PTP_INTERFACE}]" /etc/linuxptp/ptp4l.conf

          exec ptp4l -f /etc/linuxptp/ptp4l.conf -m

  ros2_dev:
    build: .
    container_name: ros2_jazzy_container
    network_mode: host
    #depends_on:
    #  - ptp-grandmaster
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./src:/ros2_ws/src
      - ./config:/ros2_ws/config
      - ./output_data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./output_data:/data
      - ws_build:/ros2_ws/build
      - ws_install:/ros2_ws/install
      - ws_log:/ros2_ws/log
      - ${HOME}/.Xauthority:/root/.Xauthority
      - ./config/gnss/:/opt/ros/jazzy/share/septentrio_gnss_driver/config/
      - ./.env:/ros2_ws/src/.env
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    devices:
      - /dev/serial/by-id/usb-Septentrio_Septentrio_USB_Device_0100014416-if00:/dev/gps-ntrip
      - /dev/serial/by-id/usb-Septentrio_Septentrio_USB_Device_0100014416-if02:/dev/gps-control
    stdin_open: true
    tty: true
    privileged: true
    command: >
      bash -lc "source /entrypoint.sh &&
      ros2 launch radas_bringup bringup.launch.py"
    group_add:
      - dialout

volumes:
  ws_build:
  ws_install:
  ws_log:
